name: 'YAML Schema Validator'
description: 'Validate YAML files in a repo according to settings'
outputs:
  invalidFiles: 
    description: 'Comma separated list of files that failed the schema validation'
runs:
  using: 'node12'
  main: 'lib/index.js'
branding: 
  icon: 'check'
  color: orange
